//! The per-RTM `Config` trait — the kernel seam.

use crate::audit::AuditLogger;
use crate::error::DispatchError;
use crate::event::Event;
use crate::origin::OriginTrait;
use crate::time::TimeSource;

/// Per-RTM configuration trait.
///
/// Every RunTime Module (RTM) defines its own `Config` extending this one
/// with the associated types and [`crate::Get`] parameters it needs. The
/// runtime composer (hand-written today, generated by `compose_runtime!`
/// in Phase 3) supplies a concrete type that implements `Config` and all
/// RTM-specific extension traits.
pub trait Config: 'static {
    /// Stable identifier for this module, used in errors, events, and audit
    /// log entries.
    const MODULE: &'static str;

    /// The runtime-wide aggregate event type, into which each module's local
    /// event composes.
    type RuntimeEvent: From<Self::Event>;

    /// Module-local event type emitted by this RTM.
    type Event: Event;

    /// Module-local error type returned from dispatches.
    type Error: core::error::Error + Send + Sync + 'static + Into<DispatchError>;

    /// Origin type carried by every dispatch.
    type Origin: OriginTrait;

    /// Time source for audit timestamps and latency measurement.
    type Time: TimeSource;

    /// Audit log sink for compliance-relevant events.
    type Audit: AuditLogger;
}
